##########################################################
##################  所有profile共有的配置  #################
##########################################################
###################  项目启动端口  ###################

spring:
  logging:
    level:
      root: INFO
    path: D:/logs/springboot-aop

nacos:
  config:
    server-addr: 127.0.0.1:8848
#####################################################################
########################  开发环境profile  ##########################
#####################################################################


